### ISSUE TITLE
[Question] Why deploying the applications to different providers

### ISSUE THREAD

**Issue by olivierobert** [nhantran3395/scrapper#48]
The client application is deployed to Vercel while the API client application is deployed to Render. Having two hosting providers introduces more complexity. So can you explain the rationale for this techical decision? Which issues did you run into?

> [!Note]
> Having these details in the README would be a great adition.

**Comment by nhantran3395** [comment]
Hi @olivierobert 

This is a fair question.

While both Vercel and Render alone can be used to deploy these 2 web and API apps, due to the limitation that each platform has, I was thinking that using a combination of Vercel deployment for the Web and Render deployment for the API would be the most suitable:

_**Web deployment:**_

- Vercel is a service specialized in deploying Next.js applications, any Next.js deploying to Vercel would be seamless, mostly not requiring any further configurations
- Render can be used to deploy static web pages with CDN set up, however, will not fully support Next.js application. In order to deploy the frontend written with Next.js to Render, I would need to use the `Static Exports` feature of Next.js https://nextjs.org/docs/pages/building-your-application/deploying/static-exports, which will take some time to set up and didn't choose

_**API deployment:**_

- Vercel, although their platform can be used to deploy an Express.js server, it is stated in the doc that it is not a good practice or recommended to do so https://vercel.com/guides/using-express-with-vercel#serverless-computing. Their use case is more suitable for serverless usage.
- Render can easily deploy the Node.js Express application. Also, I hosted an instance of the PostgreSQL database on Render.

So, in order to reduce the time needed in configuring and setting up deployments, I chose Vercel to deploy the Web app and Render to deploy the API app. Both are free (for this usage) and offer convenient integration with GitHub for CI

**Comment by nhantran3395** [comment]
On the reason for choosing Next.js over plain React when building the web app, Next.js has built-in support for routing and many other things out of the box, so using it will save time doing setup for the frontend app. I also have some other occasions that I use Next.js to build mini demos or MVPs like this, so I feel more comfortable about using this set up.

**Comment by nhantran3395** [comment]
> Note
> Having these details in the README would be a great adition.

Nice, I will raise a PR to add these descriptions to README

**Comment by nhantran3395** [comment]
Hi @olivierobert : I raised this PR to update the README for https://github.com/nhantran3395/scrapper/pull/49. Please have a look.

**Comment by olivierobert** [comment]
@nhantran3395 Thanks for the detailed explanation. For a future project, you might want to consider fly.io as it allows you to deploy Next.JS (https://fly.io/docs/js/frameworks/nextjs/) and Node.JS apps (+ having one database) on the free tier 😉

**Comment by nhantran3395** [comment]
Hi Olivier: Thanks for the suggestion! fly.io will be perfect for this kind of use case, I will definitely try it next time.
